services:
  db:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - ./data/virtuoso:/data
    ports:
      - "8890:8890"
      - "1111:1111"  
    networks:
      - backend  
      
  gatekeeper:
    image: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/static:/usr/share/nginx/html
    ports:
      - "3001:80"
    environment:
      - NGINX_PORT=80
    networks:
      - backend
    depends_on:
      - "web"
      - "admin"

  web:
    build: ./ontobrapi-web
    ports:
      - "3002:3000"
    volumes:
      - ./.config.json:/usr/src/app/.config.json
      - ./uploads:/usr/src/app/uploads   
      - ./.git/modules/ontobrapi-web/FETCH_HEAD:/usr/src/app/.FETCH_HEAD
    depends_on:
      - db
      - validator
    networks:
      - backend

  admin:  
      build: ./ontobrapi-admin
      ports:
        - "3003:3000"
      volumes:
        - ./.config.json/:/usr/src/app/.config.json
        - ./.git/modules/ontobrapi-admin/FETCH_HEAD:/usr/src/app/.FETCH_HEAD
      depends_on:
        - db
        - mongo
      networks:
        - backend

  brapi:  
      build: ./ontobrapi-brapi
      ports:
        - "3004:3000"
      volumes:
        - ./.config.json/:/usr/src/app/.config.json
        - ./.git/modules/ontobrapi-brapi/FETCH_HEAD:/usr/src/app/.FETCH_HEAD
      depends_on:
        - mongo
      networks:
        - backend

  validator:
     build: ./validator
     ports:
       - "3004:8080"
     volumes:
       - ./uploads/uploadedfiles:/usr/src/app/external   
     networks:
       - backend

  mongo:
    image: mongo
      #remove port in dev
    ports:
      - 27017:27017
      #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - backend

  #cache:
 

networks:
  backend:
    driver: bridge

#docker-compose down gatekeeper; docker-compose up gatekeeper -d; docker-compose logs -f gatekeeper;
#docker exec -it ontobrapi-gatekeeper-1 /bin/bash  
