version: '3'
services:
  db:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - ./data/virtuoso:/data
    ports:
      - "8890:8890"
      - "1111:1111"  
  web:
    build: ./ontoBrAPI-node-docker
    ports:
      - "3001:3000"
